
```{r setup}
library(ggplot2)
library(magrittr)

```


```{r multiqc-import}
multiqc_files <- list.files('../PIPELINES/osaGFP-CnR/multiqc_data', full.names = T, pattern = '*.txt')

multiqc <- purrr::map(multiqc_files, ~ read.delim(.x, header = T))
multiqc <- lapply(multiqc_files, read.delim) 
names(multiqc) <- sapply(stringr::str_split(multiqc_files,'/|_|\\.'), function(x) paste(x[8],x[9],sep ='.'))

#logs_files <- c(list.files('Logs', full.names = T, pattern = '*.txt'), list.files('Logs', full.names = T, pattern = '*.tsv'))
#
#
#logs <- purrr::maplogs_filess, ~ read.delim(.x, header =TT)

#multiqc <- lapply(multiqc_data, read.delim) 
##names(multiqc) <- sapply(stringr::str_split(multiqc_data,'/|_|\\.'), function(x) paste(x[1],x[4],sep ='.'))


```
# alignment and duplicate filtering stats 
```{r}

samtools <- multiqc$multiqc.samtools %>%
  dplyr::mutate(sample.id = paste(stringr::str_split_fixed(Sample, "-|_", n = 8)[,1],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,6],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,7], sep = "."),
                filter = stringr::str_split_fixed(Sample, "_", n = 3)[,3], .before = 1)

bowtie <- multiqc$multiqc.bowtie2 %>%
  dplyr::mutate(sample.id = paste(stringr::str_split_fixed(Sample, "-|_", n = 8)[,1],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,6],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,7], sep = "."), 
                filter = stringr::str_split_fixed(Sample, "_", n = 3)[,3], .before = 1)

picard <- multiqc$multiqc.picard %>%
  dplyr::mutate(sample.id = paste(stringr::str_split_fixed(Sample, "-|_", n = 8)[,1],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,6],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,7], sep = ".")) 

bowtie %>%
  reshape2::melt() %>%
  dplyr::filter(variable != 'total_reads' & variable != 'overall_alignment_rate' & variable != 'paired_total') %>%
  dplyr::mutate(variable = factor(variable, levels = c('paired_total', 'paired_aligned_one', 'paired_aligned_multi','paired_aligned_none'))) %>%
  ggplot(aes(sample.id, value, fill = variable)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label = round(value/1000000,2)), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c('#78c4ff','#4873e8','#8c8c8c')) +
  ylab('read pairs (millions)') +
  theme(axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank()) 

ggsave('rOut/QC/bowtie.png', width = 9, height = 5, dpi = 300)

dplyr::inner_join(bowtie, samtools, by = 'sample.id')

samtools %>%
  reshape2::melt() %>%
  dplyr::filter(variable == 'mapped_passed') %>%
  ggplot(aes(sample.id, value, fill = filter)) +
  geom_bar(stat = 'identity', position = position_dodge()) + 
  geom_text(aes(label = round(value/1000000/2, 2)), position = position_dodge(0.9), vjust = -0.5) +
  scale_fill_manual(values = c('#036ffc','#519bfc','#96c4ff')) + 
  ylab('read pairs (millions)') +
  theme(axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank())
ggsave('rOut/QC/dups.png', width = 9, height = 5, dpi = 300)

samtools

```
# fastqc screen
```{r multiqc_pies}
#multiqc$multiqc.fastq %>% reshape2::melt() %>% dplyr::filter(grepl('percentage',variable))
mycolors = colorRampPalette(RColorBrewer::brewer.pal(13, 'Spectral'))(13)
mycolors
multiqc.fastq.melt <- multiqc$multiqc.fastq %>%
  reshape2::melt() %>%
  dplyr::filter(grepl('percentage', variable)) %>%
  dplyr::mutate(sample.id = paste(stringr::str_split_fixed(Sample, "-|_", n = 8)[,1],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,6],
                                  stringr::str_split_fixed(Sample, "-|_", n = 8)[,7], sep = "_")) 

#unique(multiqc.fastq.melt$sample.id)
pie_fun <- function(sampleid, df) {
  df %>% 
    dplyr::filter(sample.id == sampleid) %>%
    ggplot(aes(sample.id, value, fill = variable)) +
    geom_bar(stat = 'identity', width = 1) + 
    coord_polar(theta = 'y') +
    scale_fill_manual(values = mycolors)
    ggsave(paste0('rOut/QC/',sampleid,'-multiqc.png'), width = 7, height = 4, dpi = 300)
}

lapply(unique(multiqc.fastq.melt$sample.id), function(x) pie_fun(sampleid = x, df = multiqc.fastq.melt))


```

