```{r}
library(magrittr)
library(GenomicRanges)
library(ggplot2)
load('rData/sheets.rda')
source('~/NystLib/R/peakUtils.R')
source('utils.R')


cnr.ss


#faire.ss <- dplyr::bind_rows(faire.osaDeGrad.ss, faire.wt.ss)
faire.peaks <- getPeakData(faire.ss, by = 'grp', narrowPeak_colname = 'peaks')


faire.ss
mcols(faire.peaks %>% GRanges())


faire.peaks <- getPeakData(faire.ss, by = 'id', narrowPeak_colname = 'peaks')
faire.byGrp <- faire.peaks %>% GRanges() %>% split(., mcols(.)$grp)
faire.byEx <- faire.peaks %>% GRanges() %>% split(., mcols(.)$experiment)

faire.union <- faire.byGrp %>%
  unlist() %>%
  reduce()

faire.byGrp <- lapply(faire.byGrp, function(x) grp_qFilter(x, quantil = 0.75, operation = 'subsetByOverlaps'))




### get CUT&RUN peaks
cnr.peaks <- getPeakData(cnr.ss, by = 'id', narrowPeak_colname = 'peak_allFrags')
cnr.byID <- cnr.peaks %>% GRanges() %>% split(., mcols(.)$id)
cnr.byGrp <- cnr.peaks %>% GRanges() %>% split(., mcols(.)$grp)


cnr.byGrp <- lapply(cnr.byGrp, function(x) grp_qFilter(x, quantile = 0.75, operation = 'subsetByOverlaps'))

cnr.union <- cnr.byID %>%
  unlist() %>%
  reduce()
```


```{r scratch-done}


#function to filter qValues - set at 75% cutoff 
#takes grouped FAIRE granges object - ie. all replicates for same sample - and filters out bottom 25% peaks by qval per replicate
qFilter <- function(df, id) {
  df %<>% data.frame() %>% dplyr::filter(id == !!id) #filter peak list to specific replicate, "!!" evaluates variable
  q <- quantile(df$qValue, probs = 0.75) #find the 75% qVal
  df.filtered <- df %>% 
    #dplyr::filter(qValue >= q) %>% 
    dplyr::mutate(qCutoff = q) 
  
  return(df.filtered) #return the filtered peak list
} 

#wrapper to pass faire peak lists (grangeslist) by experiment with replicate ids to qFilter()
grp_qFilter <- function(x) {
  grp <- x$grp
  ids <- unique(x$id) #unique replicate ids
  
  #for each unique replicate id, pass experiment peak granges and replicate name to qFilter, then bind the output list
  grp.filtered <- lapply(ids, function(y) qFilter(x, y)) 
  
  grp.list <- grp.filtered %>% GenomicRanges::GRangesList()
  
  grp.repShared <- Reduce(IRanges::subsetByOverlaps, grp.list) #takes grangeslist of qval filtered peaks and returns a granges object with only regions shared between replicates
  
  return(grp.repShared)  
}

faire.byGrp <- lapply(faire.byGrp, function(x) grp_qFilter(x)) 

faire.qF
```


```{r}

faire.df <- faire.union %>%
  data.frame() %>%
  dplyr::filter(!seqnames %in% c('chr4','chrY','chrM')) %>% #drop regions from potentially problematic chromosomes
  dplyr::mutate(peak = 1:nrow(.),
                assay = 'FAIRE',
                WT.3LW = ifelse(GRanges(.) %over% faire.byGrp$wt.3LW, T, F),
                WT.6h = ifelse(GRanges(.) %over% faire.byGrp$wt.6h, T, F),
                WT.24h = ifelse(GRanges(.) %over% faire.byGrp$wt.24h, T, F),
                WT.44h = ifelse(GRanges(.) %over% faire.byGrp$wt.44h, T, F),
                osaGFP.control = ifelse(GRanges(.) %over% faire.byGrp$osaGFP.deGrad_control_faire, T, F),
                osaGFP.deGrad = ifelse(GRanges(.) %over% faire.byGrp$osaGFP.deGrad_nubG4_faire, T, F)) %>%
  dplyr::filter(WT.3LW | WT.6h | WT.24h | WT.24h | WT.44h | osaGFP.control | osaGFP.deGrad) %>% #drop regions that don't have a good quality reproducible peak called
#get osaGFP deGrad cnr bigwig scores...
  dplyr::mutate(osaGFP.rep1.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                osaGFP.rep2.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                yw.rep1.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                yw.rep2.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
#get faire bigwig scores... 
                faire.3LW = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_3LW',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)),
                faire.6h = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_6h',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)),
                faire.24h = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_24h',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)),
                faire.44h = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_44h',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)))
             
cnr.df <- cnr.union %>%
  data.frame() %>%
  dplyr::filter(!seqnames %in% c('chr4','chrY','chrM')) %>% #drop regions from potentially problematic chromosomes
  dplyr::mutate(peak = 1:nrow(.),
                assay = 'CnR',
                osa.cnr = ifelse(GRanges(.) %over% cnr.byGrp$osaGFP.sup, T, F),
                yw.cnr = ifelse(GRanges(.) %over% cnr.byGrp$yw.sup, T, F)) %>%
  dplyr::filter(osa.cnr | yw.cnr) %>% #drop regions that don't have a good quality reproducible peak called
#get osaGFP deGrad cnr bigwig scores...
  dplyr::mutate(osaGFP.rep1.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                osaGFP.rep2.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                yw.rep1.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                yw.rep2.spikeNorm = get_bw_score(cnr.ss[cnr.ss$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
#get faire bigwig scores... 
                faire.3LW.zScore = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_3LW',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)),
                faire.6h.zScore = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_6h',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)),
                faire.24h.zScore = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_24h',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)),
                faire.44h.zScore = get_bw_score(faire.wt.ssPool[faire.wt.ssPool$baseName == 'wt_44h',]$bigwig_rpgcNorm_zNorm[1], GRanges(.)))


cnr.df %>% dplyr::filter(osa.cnr & !yw.cnr)
write.table(cnr.df %>% dplyr::filter(osa.cnr & !yw.cnr) %>% dplyr::select(seqnames, start, end), 'test.bed', col.names = F, row.names = F, quote = F)



  dplyr::mutate(osaGFP.rep2.bw = get_bw_score(cnr.ss[cnr.ss$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
faire.ss
cnr.ss
faire.ss[faire.ss$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep1',]
                osaGFP.rep2.zScore = get_bw_score(sampleSheet[sampleSheet$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep2',]$zNorm_bigwig_allFrags_rpgcNorm[1], GRanges(.)),
                yw.rep1.All.zScore = get_bw_score(sampleSheet[sampleSheet$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep1',]$zNorm_bigwig_allFrags_rpgcNorm[1], GRanges(.)),
                yw.rep2.All.zScore = get_bw_score(sampleSheet[sampleSheet$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep2',]$zNorm_bigwig_allFrags_rpgcNorm[1], GRanges(.)),
                osaGFP.rep1.All.spikeNorm = get_bw_score(sampleSheet[sampleSheet$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                osaGFP.rep2.All.spikeNorm = get_bw_score(sampleSheet[sampleSheet$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                yw.rep1.All.spikeNorm = get_bw_score(sampleSheet[sampleSheet$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                yw.rep2.All.spikeNorm = get_bw_score(sampleSheet[sampleSheet$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags_sacCer3_spikeNorm[1], GRanges(.)),
                osaGFP.rep1.All.bw = get_bw_score(sampleSheet[sampleSheet$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags[1], GRanges(.)),
                osaGFP.rep2.All.bw = get_bw_score(sampleSheet[sampleSheet$baseName == 'osaGFP-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags[1], GRanges(.)),
                yw.rep1.All.bw = get_bw_score(sampleSheet[sampleSheet$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep1',]$bigwig_allFrags[1], GRanges(.)),
                yw.rep2.All.bw = get_bw_score(sampleSheet[sampleSheet$baseName == 'yw-3LW-wing-aGFP-CnR-sup-rep2',]$bigwig_allFrags[1], GRanges(.)),
                faire.3lw = get_bw_score(fairePoolSheet[fairePoolSheet$grp == 'wt.3LW',]$bigwig_rpgcNorm_zNorm, GRanges(.)),
                faire.6h = get_bw_score(fairePoolSheet[fairePoolSheet$grp == 'wt.6h',]$bigwig_rpgcNorm_zNorm, GRanges(.)),
                faire.18h = get_bw_score(fairePoolSheet[fairePoolSheet$grp == 'wt.18h',]$bigwig_rpgcNorm_zNorm, GRanges(.)),
                faire.24h = get_bw_score(fairePoolSheet[fairePoolSheet$grp == 'wt.24h',]$bigwig_rpgcNorm_zNorm, GRanges(.)),
                faire.44h = get_bw_score(fairePoolSheet[fairePoolSheet$grp == 'wt.44h',]$bigwig_rpgcNorm_zNorm, GRanges(.))) %>%
                

```

